apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: testing-app-ingress
  namespace: testing
spec:
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - auth-service
      - tasks-service
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: testing-postgres-auth-ingress
  namespace: testing
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: postgres-auth
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          cnpg.io/cluster: postgres-auth
    - podSelector:
        matchLabels:
          app: auth-service
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: testing-postgres-tasks-ingress
  namespace: testing
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: postgres-tasks
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          cnpg.io/cluster: postgres-tasks
    - podSelector:
        matchLabels:
          app: tasks-service
