{{- if .Values.prometheus.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.namespace }}-{{ .Values.name }}-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.namespace }}-{{ .Values.name }}-prometheus
subjects:
- kind: ServiceAccount
  name: {{ .Values.name }}-prometheus
  namespace: {{ .Values.namespace }}
{{- end }}
