{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.name }}-prometheus-config
  namespace: {{ .Values.namespace }}
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s

    scrape_configs:
      - job_name: '{{ .Values.name }}'
        static_configs:
          - targets: ['{{ .Values.name }}:{{ .Values.service.port }}']
        metrics_path: '/metrics'

      - job_name: 'postgres'
        static_configs:
          - targets: ['{{ .Values.postgres.name }}-rw:5432']
{{- end }}
