{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.name }}-prometheus-storage
  namespace: {{ .Values.namespace }}
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: {{ .Values.prometheus.storage.storageClass }}
  resources:
    requests:
      storage: {{ .Values.prometheus.storage.size }}
{{- end }}
