{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-prometheus
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-prometheus
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    name: http
  selector:
    app: {{ .Values.name }}-prometheus
{{- end }}
