{{- if .Values.prometheus.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.name }}-prometheus
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}-prometheus
{{- end }}
