apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prod-app-ingress
  namespace: prod
spec:
  podSelector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - auth-service
      - tasks-service
      - grafana
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: ingress-nginx
    - podSelector:
        matchLabels:
          app: prometheus
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prod-postgres-auth-ingress
  namespace: prod
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: postgres-auth
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          cnpg.io/cluster: postgres-auth
    - podSelector:
        matchLabels:
          app: auth-service
    - podSelector:
        matchLabels:
          app: prometheus
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prod-postgres-tasks-ingress
  namespace: prod
spec:
  podSelector:
    matchLabels:
      cnpg.io/cluster: postgres-tasks
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          cnpg.io/cluster: postgres-tasks
    - podSelector:
        matchLabels:
          app: tasks-service
    - podSelector:
        matchLabels:
          app: prometheus
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: prod-prometheus-ingress
  namespace: prod
spec:
  podSelector:
    matchLabels:
      app: prometheus
  policyTypes:
  - Ingress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: grafana
