{{- if and .Values.grafana.enabled .Values.grafana.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-grafana-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    {{- range $key, $value := .Values.grafana.ingress.annotations }}
    {{ $key }}: {{ $value | quote }}
    {{- end }}
spec:
  ingressClassName: {{ .Values.grafana.ingress.className }}
  {{- if .Values.grafana.ingress.tls.enabled }}
  tls:
  - hosts:
    - {{ .Values.grafana.ingress.host }}
    secretName: {{ .Values.grafana.ingress.tls.secretName }}
  {{- end }}
  rules:
  - host: {{ .Values.grafana.ingress.host }}
    http:
      paths:
      - path: {{ .Values.grafana.ingress.path }}
        pathType: {{ .Values.grafana.ingress.pathType }}
        backend:
          service:
            name: {{ .Values.name }}-grafana
            port:
              number: 3000
{{- end }}
